# Generated by Django 3.0.7 on 2020-06-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
            ],
        ),
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs', models.CharField(max_length=64, verbose_name='文件系统')),
                ('size', models.BigIntegerField(verbose_name='大小')),
                ('used', models.BigIntegerField(verbose_name='已使用')),
                ('avail', models.BigIntegerField(verbose_name='可用')),
                ('usage_rate', models.SmallIntegerField(verbose_name='使用率')),
                ('mounted', models.CharField(max_length=256, verbose_name='挂载点')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server')),
            ],
        ),
    ]
