# Generated by Django 3.0.7 on 2020-06-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_filesystem_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iface_name', models.CharField(max_length=32, verbose_name='接口名')),
                ('ip', models.CharField(max_length=32, verbose_name='IP 地址')),
                ('netmask', models.CharField(max_length=32, verbose_name='子网掩码')),
                ('broadcast', models.CharField(max_length=32, verbose_name='广播地址')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server')),
            ],
        ),
    ]
