# Generated by Django 3.0.7 on 2020-06-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_network_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='变更内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Server', verbose_name='服务器')),
            ],
        ),
    ]
