# Generated by Django 3.0.7 on 2020-06-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assetsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='总大小')),
                ('used', models.IntegerField(verbose_name='已使用')),
                ('free', models.IntegerField(verbose_name='空闲')),
                ('type', models.IntegerField(verbose_name='类型')),
                ('shared', models.IntegerField(verbose_name='共享')),
                ('buff_cache', models.IntegerField(verbose_name='缓冲和缓存')),
                ('available', models.IntegerField(verbose_name='可用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server')),
            ],
        ),
    ]
