# Generated by Django 3.0.7 on 2020-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200625_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='available',
            field=models.IntegerField(null=True, verbose_name='可用'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='buff_cache',
            field=models.IntegerField(null=True, verbose_name='缓冲和缓存'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='shared',
            field=models.IntegerField(null=True, verbose_name='共享'),
        ),
    ]
