# Generated by Django 3.0.7 on 2020-06-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='type',
            field=models.CharField(default='basic', max_length=32, verbose_name='类型'),
        ),
    ]
