# Generated by Django 3.0.7 on 2020-06-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_basic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_update_date',
            field=models.DateField(null=True, verbose_name='最近汇报时间'),
        ),
    ]
