# Generated by Django 3.0.7 on 2020-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200625_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU个数'),
        ),
        migrations.AddField(
            model_name='server',
            name='kernel_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='内核版本'),
        ),
        migrations.AddField(
            model_name='server',
            name='uname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='系统类型'),
        ),
        migrations.AddField(
            model_name='server',
            name='version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='发行版'),
        ),
        migrations.DeleteModel(
            name='Basic',
        ),
    ]
