# Generated by Django 3.0.7 on 2020-06-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200627_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='cabinet_num',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='机柜号'),
        ),
        migrations.AddField(
            model_name='server',
            name='cabinet_order',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='机柜中序号'),
        ),
        migrations.AddField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.IDC', verbose_name='机房'),
        ),
    ]
